[workspace]
members = [ "node" ]

[package]
name = "tauri-cli"
version = "2.0.0-alpha.10"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2021"
rust-version = "1.65"
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.app"
repository = "https://github.com/tauri-apps/tauri"
description = "Command line interface for building Tauri apps"
include = [
  "src/",
  "/templates",
  "scripts/",
  "*.json",
  "*.rs",
  "tauri.gitignore",
  "tauri-dev-watcher.gitignore",
  "LICENSE*"
]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/tauri-cli-v{ version }/cargo-tauri-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[dependencies]
tauri-mobile = { version = "0.5.1", default-features = false }
textwrap = { version = "0.11.0", features = [ "term_size" ] }
jsonrpsee = { version = "0.16", features = [ "server" ] }
jsonrpsee-core = "0.16"
jsonrpsee-client-transport = { version = "0.16", features = [ "ws" ] }
jsonrpsee-ws-client = { version = "0.16", default-features = false }
thiserror = "1"
sublime_fuzzy = "0.7"
clap_complete = "4"
clap = { version = "4.0", features = [ "derive" ] }
anyhow = "1.0"
tauri-bundler = { version = "2.0.0-alpha.6", default-features = false, path = "../bundler" }
colored = "2.0"
once_cell = "1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
notify = "6.0"
notify-debouncer-mini = "0.3"
shared_child = "1.0"
duct = "0.13"
toml_edit = "0.14"
json-patch = "1.0"
tauri-utils = { version = "2.0.0-alpha.6", path = "../../core/tauri-utils", features = [ "isolation", "schema", "config-json5", "config-toml" ] }
tauri-utils-v1 = { version = "1", package = "tauri-utils", features = [ "isolation", "schema", "config-json5", "config-toml" ] }
toml = "0.5"
jsonschema = "0.16"
handlebars = "4.3"
include_dir = "0.7"
minisign = "=0.7.3"
base64 = "0.21.0"
ureq = { version = "2.5", default-features = false, features = [ "gzip" ] }
os_info = "3"
semver = "1.0"
regex = "1.6.0"
unicode-width = "0.1"
zeroize = "1.5"
heck = { version = "0.4", features = [ "unicode" ] }
dialoguer = "0.10"
url = { version = "2.3", features = [ "serde" ] }
os_pipe = "1"
ignore = "0.4"
ctrlc = "3.2"
log = { version = "0.4.17", features = [ "kv_unstable", "kv_unstable_std" ] }
env_logger = "0.9.1"
icns = { package = "tauri-icns", version = "0.1" }
image = { version = "0.24", default-features = false, features = [ "ico" ] }
axum = { version = "0.5.16", features = [ "ws" ] }
html5ever = "0.26"
kuchiki = { package = "kuchikiki", version = "0.8" }
tokio = { version = "1", features = [ "macros", "sync" ] }
common-path = "1"
serde-value = "0.7.0"
itertools = "0.10"
local-ip-address = "0.4"
css-color = "0.2"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [ "handleapi", "processenv", "winbase", "wincon", "winnt" ] }
cc = "1"

[target."cfg(unix)".dependencies]
libc = "0.2"

[profile.release]
lto = true

[features]
default = [ "rustls" ]
native-tls = [
  "tauri-bundler/native-tls",
  "tauri-mobile/native-tls",
  "ureq/native-tls"
]
native-tls-vendored = [
  "native-tls",
  "tauri-bundler/native-tls-vendored",
  "tauri-mobile/openssl-vendored"
]
rustls = [ "tauri-bundler/rustls", "tauri-mobile/rustls", "ureq/tls" ]
